import Head from "next/head";
import { type FC, type PropsWithChildren } from "react";

type Props = PropsWithChildren<{
  title?: string;
}>;
const Page: FC<Props> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title ? `${title} - ` : ""}Atharo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{children}</div>
    </>
  );
};

export default Page;
